name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Login to Docker HUB
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cdn:latest .

      - name: Push the image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cdn:latest